### ISSUE TITLE
QUESTION: what is 'post { }' ? I wasn't able to find any examples of it online.

### ISSUE THREAD

**Issue by hojoungjang** [r3za13/android-timeline-schedule-view#4]
https://github.com/r3za13/android-timeline-schedule-view/blob/18edc9dc301add118fcb36a1d721c62acb3edb09/timelinedayviewlibrary/src/main/java/com/roundtableapps/timelinedayviewlibrary/TimeLineLayoutGroup.kt#L128

**Comment by r3za13** [comment]
The UI event queue will process events in order. if you want to do something on view after layout you can use the post method. This basically queues your code after the view's measure and layout

**Comment by hojoungjang** [comment]
Thank you!

**Comment by hojoungjang** [comment]
I am wondering what these are. Are they just lambda functions assigned to a variable? I am working to create similar custom view in Java and do not really know Kotlin. Could you help me?

https://github.com/r3za13/android-timeline-schedule-view/blob/18edc9dc301add118fcb36a1d721c62acb3edb09/timelinedayviewlibrary/src/main/java/com/roundtableapps/timelinedayviewlibrary/EventView.kt#L24

**Comment by r3za13** [comment]
Yeah this is just a function and you can do same thing with an interface.
do not hesitate to open issues if you have another questions

**Comment by hojoungjang** [comment]
Thank you!
